# Generated by Django 3.2 on 2021-05-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20210504_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
