# Generated by Django 3.2 on 2021-05-04 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_animelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='animelist',
            name='video_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
