# Generated by Django 3.2 on 2021-05-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_animelist_video_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Joogers',
            new_name='Joggers',
        ),
    ]
